Adding pagination and shared folders
dataiku/dss-plugin-googledrive pull request #5
Opened 2021-04-21 10:21 UTC by alexbourret

2021-04-21 16:01 UTC, MayeulRousselet requested changes

2021-04-21 16:01 UTC, MayeulRousselet commented on python-lib/dku_googledrive/session.py
> +                    request = self.drive.files().list(**kwargs).execute()
From what i've seen in the doc (here: https://googleapis.github.io/google-api-python-client/docs/epy/index.html), execute can have a num_retries parameters to automatically handles retries for you.

2021-04-21 16:44 UTC, alexbourret commented on python-lib/dku_googledrive/session.py
> +                while initial_call or next_page_token:
They advice both methods : https://developers.google.com/drive/api/v2/reference/files/list#examples

2021-04-22 08:52 UTC, MayeulRousselet approved these changes

2021-04-22 08:52 UTC, merged